import { Dependent } from './dependent';
import { Term } from './term';
import { DocumentFile } from './document-file';
import { Project } from './project';
import { Institute } from './institute';
import { EmploymentRelationship } from './employment-relationship';
import { Benefit } from './benefit';
import { PaymentInformation } from './payment-information';

export class Collaborator {
  id?: number;
  active?: boolean;
  name?: string;
  socialName?: string;
  cpf?: string;
  rg?: string;
  rgEmitter?: string;
  pis?: string;
  maritalStatus?: string;
  nationality?: string;
  birthdate?: string;
  email?: string;
  personalEmail?: string;
  phone?: string;
  motherName?: string;
  fatherName?: string;
  address?: string;
  district?: string;
  cep?: string;
  city?: string;
  state?: string;
  emergencyContactName1?: string;
  emergencyParentage1?: string;
  emergencyContactPhone1?: string;
  emergencyContactName2?: string;
  emergencyParentage2?: string;
  emergencyContactPhone2?: string;
  academicDegree?: string;
  university?: string;
  lattes?: string;
  job?: string;
  image?: string;
  gender?: string;
  dependents?: Dependent[];
  activities?: string;
  terms?: DocumentFile[];
  jobTitle?: string;
  admission?: string;
  shutdown?: string;
  projectAlocated?: Project;
  institute?: Institute;
  employmentRelationship?: EmploymentRelationship;
  employment?: string;
  salary?: string;
  workload?: string;
  benefits?: Benefit[];
  documents?: DocumentFile[];
  payments?: PaymentInformation[];
  dataPercentage?: number;
}
